### ISSUE TITLE
Unauthorized PseudoTV Live version

### ISSUE THREAD

**Issue by Lunatixz** [RyskiMod/NTV#1]
Could you please remove your unauthorized version of my plugin PseudoTV Live. You may or maynot be aware that your manipulation of version numbers can Hijack my code. This would leave me in a position to push code alerting users to uninstall your plugins and repositories. A cycle of events that is counter productive to all.

I'd also like to keep my work far removed from any illegal plugins in circulation. Combining the two only discourages the continuation of the project since I actively discourage the use of pirated plugins.

Users can freely download my work via my beta repository.

Thank you.

**Comment by RyskiMod** [comment]
I will remove your slightly modified version of the plugin when im next at my pc.
No offense was meant and the version bump was only to fix a problem within our builds which are now private.
Huge respect for such a great addon

**Comment by Lunatixz** [comment]
THX, please report any bugs encounted and I'll fix them... My builds are public, nothing is private except for beta code not meant for the general audience.
